name: Docker Image CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
   - name: Check out code
    uses: actions/checkout@v2
    run:  cd myProjectFolder docker build -t .
